- ACDC-fog
- ACDC-night
- ACDC-rain
- ACDC-snow
- ADE20K
- CS
- MUSES-clear
- MUSES-fog
- MUSES-rain
- MUSES-snow
- BDD
- MV
# - muses-clear-day
# - muses-clear-night
# - muses-rain-day
# - muses-rain-night
# - muses-fog-day
# - muses-fog-night
# - muses-snow-night
# - muses-snow-day
# - cs-normal
# - bdd
# - mv
# - a150
# - idd
# - pc59
# - coconutL
# - nyu
